### PR TITLE
Implement OAuth

### PR DESCRIPTION
**Pull request by coolultra1**
It was sooooo annoying you had to reenter your creds every time, I'd misstype somehow EVERY SINGLE TIME, so I just implemented OAuth @Zverik

### CODE REVIEW

**Comment by coolultra1** [comment]
Still pretty unsure whether to just let every user create an OAuth app of their own or to just create one public one

**Comment by coolultra1** [comment]
Yea, I kinda spent some time thinking, which I like and I think there just should be one public OAuth app for everyone, not like anyone can abuse it -- App token is always going to be stored in the same place with the actual user's auth token for that app, so there is no difference in security. Making everyone create an OAuth app of their own is just a lot of hastle for everyone.

Though this is not my thing to decide, maybe you don't want OAuth at all, Zverik?

**Comment by coolultra1** [comment]
@Zverik you ok?

**Comment by Zverik** [comment]
Emil, thanks for you work on adding OAuth to the script. I have to close this because 1) OAuth2 is the way, 2) I wrote a universal library [cli-oauth2](https://github.com/Zverik/cli-oauth2) that is even simpler to work with, and updated the script to use it.

**Pull request closed without merging**
